import android.app.AlertDialog
import android.content.Context
import android.os.Handler
import android.os.Looper
import android.view.LayoutInflater
import android.view.View
import android.widget.PopupWindow
import com.example.griffin.R
import com.example.griffin.mudels.Thermostst
import com.example.griffin.mudels.udp_thermostat_for_scenario
